account/urls.py
from django.urls import path
from .views import loginView, registerView, logoutView

app_name = 'account' 
urlpatterns = [

    path('login/',loginView,name="login"),
    path('register/',registerView,name="register"),
    path('logout/',logoutView,name="logout"),

]

app/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.index, name="home"),
    path('room/detail/<int:pk>/',views.DetailRoom.as_view(), name="room-details"),
    path('service/detail/<int:pk>/',views.DetailService.as_view(), name="service-details"),
    path('equipment/detail/<int:pk>/',views.DetailEquipment.as_view(), name="equipment-details"),
    path('reserver/<int:id>/<str:ressource_type>/',views.reserver, name="reserver"),
    path('my_reservations/',  views.my_reservation, name="my-reservations"),
    path("cancel_reservation/<int:reservation_id>/", views.cancel_reservation, name="cancel"),
    path('delete/<int:reservation_id>/', views.delete_reservation, name='delete_reservation'),
    path('waitlist/<str:resource_model>/<int:resource_id>/', views.add_to_waitlist, name="add-to-waitelist"),
    path("user_waitlist/",views.view_user_waitlist, name="my-waitlite")
    ]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('',include('account.urls')),
]

app/templates/app/_partials/carousel.html

<style>
  .carousel-item img {
  height: 50vh; /* Modifie la hauteur de l'image à 50% de la hauteur de la fenêtre */
  object-fit: cover; /* Pour s'assurer que l'image remplit le conteneur sans déformation */
}

.carousel-caption {
  bottom: 20%; /* Ajustez cette valeur pour placer les légendes plus haut ou plus bas */
}
</style>


<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>

  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://img.freepik.com/free-photo/female-tourist-using-mobile-nfc-payment-pos-terminal_482257-98854.jpg?t=st=1730291656~exp=1730295256~hmac=12573f19ea87026ea92fa811e8f160e9eb3cb5018aee4d24d7b5611107592c47&w=1060" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h2 class="text-warning">Réservez chez nous tout ce que vous voulez en toute surété </h2>
        <p>Profitez d'une expérience de réservation sans tracas pour vos besoins, où que vous soyez.</p>
      </div>
    </div>

    <div class="carousel-item">
      <img src="https://cdn.pixabay.com/photo/2023/06/22/07/59/women-8080878_960_720.png" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h2 class="text-warning">Votre confort, notre priorité !</h2>
        <p>"Des équipements modernes et un service personnalisé pour un séjour inoubliable.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://media.istockphoto.com/id/488377600/fr/photo/voyage-de.jpg?s=2048x2048&w=is&k=20&c=65VvPWSUBBkWfYs2RCks8KWPnCmMj4TGrmOkEBBZNEg=" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h2 class="text-warning">Explorez, Réservez, Détendez-vous !</h2>
        <p>Réservez vos services en quelques clics et laissez-nous prendre soin du reste.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/templates/app/_partials/meta_data.html
    <meta charset="UTF-8">
    <meta name="description" content="Plateforme de réservation hotel Etykam">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Hotel Reservation system</title>

app/templates/app/_partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
      <a class="navbar-brand" href="#">Kamano Réservations</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav me-auto">
              <!-- Lien Accueil -->
              <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Accueil</a>
              </li>
              
              <!-- Lien Mes Réservations avec badge -->
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'my-reservations' %}">
                      Mes Réservations
                      <span class="badge bg-primary">
                          {{ request.user.reservations.count|default:0 }}
                      </span>
                  </a>
              </li>

              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'my-waitlite' %}">File D'attente</a>
            </li>
          </ul>

          <!-- Affichage utilisateur (Connexion/Déconnexion) -->
          <ul class="navbar-nav">
              {% if request.user.is_authenticated %}
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'account:logout' %}">Se déconnecter ({{ request.user.username }})</a>
                  </li>
              {% else %}
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'account:login' %}">Se connecter</a>
                  </li>
              {% endif %}
          </ul>
      </div>
  </div>
</nav>

app/templates/app/_partials/ressources.html
<!-- Room view alls -->
<div class="row">
    <h2>Nos salles</h2>
    <hr>
    {% for room in ressources.room %}
        <div class="card border" style="width: 18rem; margin: 10px;">
            <img src="{{ room.image }}" class="card-img-top" alt="{{ room.name }}">
            <div class="card-body">
                <h5 class="card-title">{{ room.name }}</h5>
                <p class="card-text">Capacité : {{ room.capacity }} personnes</p>
                <p class="card-text">Emplacement : {{ room.location }}</p>
                <div class="row">
                    <a href="{% url 'room-details' room.pk %}" class="btn btn-primary">Réserver</a>
                </div>
            </div>
        </div>
    {% empty %}
        <p class="alert alert-info">Aucune salle disponible.</p>
    {% endfor %}
</div>
<!-- Equipments views all -->
<div class="row">
    <h2>Nos Équipements</h2>
    <hr>
    {% for equipment in ressources.equipment %}
        <div class="card border" style="width: 18rem; margin: 10px;">
            <img src="{{ equipment.image }}" class="card-img-top" alt="{{ equipment.name }}">
            <div class="card-body">
                <h5 class="card-title">{{ equipment.name }}</h5>
                <p class="card-text">{{ equipment.description|slice:':50' }}...</p>
                <p class="card-text">Maintenance requise : {{ equipment.maintenance_required|yesno:"Oui,Non" }}</p>
            <div class="row">
                <a href="{% url 'equipment-details' equipment.pk %}" class="btn btn-primary">Réserver</a>
            </div>
            </div>
        </div>
    {% empty %}
        <p class="alert alert-info">Aucun équipement disponible.</p>
    {% endfor %}
</div>


<!-- Service View all -->
<div class="row">
    <h2>Nos Services</h2>
    <hr>
    {% for service in ressources.service %}
        <div class="card border" style="width: 18rem; margin: 10px;">
            <img src="{{ service.image }}" class="card-img-top w-100" style="height:100px" alt="{{ service.name }}">
            <div class="card-body">
                <h5 class="card-title">{{ service.name }}</h5>
                <p class="card-text">Type de Service : {{ service.service_type }}</p>
                <p class="card-text">Fournisseur(s) : 
                    {% for provider in service.provider.all %}
                        {{ provider.name }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>
                <div class="row">
                    <a href="{% url 'service-details' service.pk %}" class="btn btn-primary">Réserver</a>
                </div>
            </div>
        </div>
    {% empty %}
        <p class="alert alert-info">Aucun service disponible.</p>
    {% endfor %}
</div>

Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab quasi nam quidem eaque nemo architecto dolore impedit alias necessitatibus soluta sed delectus excepturi temporibus, est nostrum, autem ullam cupiditate dicta?

app/templates/app/_partials/scripts.html
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

app/templates/app/_partials/styles.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">